name: Packer

on:
  schedule:
    # 每周日凌晨 0 点执行 Release
    - cron: 
        0 0 * * 0

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pack.zip
          path: ./Patch-Pack-CN
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pack.zip"
          tag: "Realease-${{ steps.date.outputs.date }}"
