name: Translation To GitHub

on:
  push:
    branches: ["main"]

env:
  API_KEY: c6b450a2fb51077faa022f7412d89dcb
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Translation-To-GitHub:
    name: Translation To GitHub
    runs-on: ubuntu-latest
    env:
      FILE_PATH: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: Json To Paratranz
        run: |
          python translationToGitHub.py
