name: Translation To GitHub

on:
  push:
    branches: ["main"]

env:
  API_KEY: c6b450a2fb51077faa022f7412d89dcb
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FILE_PATH: ./

jobs:
  Translation-To-GitHub:
    name: Translation To GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: Paratranz To zh_cn
        run: |
          python translationToGitHub.py
      - name: Out
        run: |
          echo ${{ steps.Translation-To-GitHub.branch }}
    outputs:
      passed: ${{ steps.Translation-To-GitHub.passed }}
      branch: ${{ steps.Translation-To-GitHub.branch }}
  Test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Work Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check-and-parse-issue.outputs.branch }}
          path: ".repo"
