name: Translation To GitHub
on:
  push:
    branches: ["main"]

env:
  API_KEY: c6b450a2fb51077faa022f7412d89dcb
  FILE_PATH: ./
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_PATH: https://github.com/Litchiiiiii/test.git

jobs:
  Translation-To-GitHub:
    name: Translation To GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: Paratranz To zh_cn
        run: |
          python translationToGitHub.py
      - name: Upload To Develop
        run: |
          git init
          git fetch origin
          git config --global user.email "1592282237@qq.com"
          git config --global user.name "Litchiiiiiii"
          git checkout develop
          git add .
          git commit -m 'paratranz上传'
          git pull origin develop --allow-unrelated-histories
          git push -u origin develop
  createPullRequest:
    runs-on: ubuntu-latest
    needs: Translation-To-GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          commit-message: Update Translation
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: develop
          delete-branch: false
          title: "[自动化]Update Translation"
          body: |
            自动化更新paratranz->github
          draft: false
