name: Translation To GitHub
on:
  push:
    branches: ["main"]

env:
  API_KEY: c6b450a2fb51077faa022f7412d89dcb
  FILE_PATH: ./
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_PATH: https://github.com/Litchiiiiii/test.git

jobs:
  Translation-To-GitHub:
    name: Translation To GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: Paratranz To zh_cn
        run: |
          python translationToGitHub.py
      - name: List
        run: |
          ls ${{ github.workspace }}
      - uses: actions/upload-artifact@v3
        with:
          name: upload
          path: ${{ github.workspace }}/Patch-Pack-CN
      - name: Upload To Develop
        run: |
          git init
          git checkout  -b develop
          git remote add origin $GIT_PATH
          git add .
          git commit -m '你的备注信息'
