# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  issues:
    types: [opened]
env:
  API_KEY: c6b450a2fb51077faa022f7412d89dcb

permissions:
  contents: read

jobs:
  check-issue-and-upload:
    if: contains(github.event.issue.labels.*.name, '自动化:json→paratranz')
    name: Check Issue And Upload
    runs-on: ubuntu-latest
    env:
      FILE_PATH: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/MuXiu1997/ParaTranz-SDK-python.git
          pip install PyGithub
      - name: Json To Paratranz
        run: |
          python main.py
  close-issue:
    name: Close Issue
    needs: check-issue-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            此模板仅由内部人员使用，已自动关闭。
